export const BoxActionTypes = {
	'SET_FACE_BOUNDARY': 'SET_FACE_BOUNDARY',
	'SET_APPAREL_BOUNDARY': 'SET_APPAREL_BOUNDARY',
	'TOGGLE_BOX': 'TOGGLE_BOX',
	'NUMBER_OF_FACES':'NUMBER_OF_FACES',
	'APPARELS_INFO': 'APPARELS_INFO',
	'APPARELS_LABEL':'APPARELS_LABEL',
	'BOUNDING_BOX': 'BOUNDING_BOX',
	'WITH_SPINNER': 'WITH_SPINNER'
}		