export const BoxActionTypes = {
	'SET_FACE_BOUNDARY': 'SET_FACE_BOUNDARY',
	'SET_APPAREL_BOUNDARY': 'SET_APPAREL_BOUNDARY',
	'TOGGLE_BOX': 'TOGGLE_BOX',
	'SET_FACE_INFO':'SET_FACE_INFO',
	'SET_APPARELS_INFO': 'SET_APPARELS_INFO',
	'SET_APPARELS_LABEL':'SET_APPARELS_LABEL',
	'SET_BOUNDING_BOX': 'SET_BOUNDING_BOX',
	'SET_WITH_SPINNER': 'SET_WITH_SPINNER'
}		